"""First migration

Revision ID: 1971a04e46a5
Revises: 4791147ab1fd
Create Date: 2022-07-14 10:12:01.606554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1971a04e46a5'
down_revision = '4791147ab1fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
