"""First migration

Revision ID: 4791147ab1fd
Revises: cdd99ec41968
Create Date: 2022-07-13 16:30:54.353684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4791147ab1fd'
down_revision = 'cdd99ec41968'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
