"""First migration

Revision ID: bc105378362d
Revises: 1971a04e46a5
Create Date: 2022-07-14 10:14:12.500608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc105378362d'
down_revision = '1971a04e46a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booknote', sa.Column('note1', sa.String(), nullable=False))
    op.drop_column('booknote', 'note')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booknote', sa.Column('note', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('booknote', 'note1')
    # ### end Alembic commands ###
