"""First migration

Revision ID: cdd99ec41968
Revises: 15972effcbd3
Create Date: 2022-07-13 16:25:42.229461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdd99ec41968'
down_revision = '15972effcbd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
