"""First migration

Revision ID: d95c36e3e568
Revises: bc105378362d
Create Date: 2022-07-14 10:32:27.955054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd95c36e3e568'
down_revision = 'bc105378362d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booknote', sa.Column('note', sa.String(), nullable=False))
    op.drop_column('booknote', 'note1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booknote', sa.Column('note1', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('booknote', 'note')
    # ### end Alembic commands ###
